name: Deploy Dart Frog App

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Dart
        uses: dart-lang/setup-dart@v1

      - name: Build and Deploy
        run: |
          dart pub global activate dart_frog_cli
          dart_frog build
          # You might need additional commands to deploy the built files

